services:
  nginx-proxy:
    container_name: nginx-proxy
    network_mode: bridge
    image: carlonicora/nginx-proxy:1.0
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./:/var/www/html:delegated
      - ./logs:/var/logs/nginx/:delegated
      - ./nginx/hosts:/etc/nginx/sites-available/:delegated
      - ./certbot/conf:/etc/letsencrypt:delegated
      - ./certbot/www:/var/www/certbot:delegated
    ports:
      - "80:80"
      - "443:443"

  letsencrypt:
    container_name: letsencrypt
    network_mode: bridge
    image: certbot/certbot
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt:delegated
      - ./certbot/www:/var/www/certbot:delegated
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
